repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.21.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: ["--fix",  "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format
        types_or: [python, pyi]

  # Check for misspells in documentation files:
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.4.2
  #   hooks:
  #     - id: codespell
  #       args:
  #         - "--skip"
  #         - ".git/*"
  #       additional_dependencies:
  #         - tomli

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
        - mdformat-front-matters
        - mdformat-gfm
        - mdformat-pyproject
        - mdformat-ruff
        # - mdformat-shfmt
        - mdformat_footnote
        - ruff
      language_version: python3.13

  ## Conventional Commits
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [pandas-stubs]
        args: ["--config-file=pyproject.toml"]
        pass_filenames: false
